# Generated by Django 5.2.5 on 2025-08-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_hectares', models.FloatField(blank=True, null=True)),
                ('grass_type', models.CharField(blank=True, max_length=50, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geo_json_data', models.TextField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag', models.CharField(db_index=True, max_length=20)),
                ('lot', models.CharField(db_index=True, max_length=20)),
                ('entry_date', models.DateField(db_index=True)),
                ('entry_weight', models.FloatField()),
                ('sex', models.CharField(max_length=1)),
                ('entry_age', models.FloatField()),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.farm')),
            ],
            options={
                'unique_together': {('ear_tag', 'lot', 'farm')},
            },
        ),
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('diet_type', models.CharField(max_length=50)),
                ('daily_intake_percentage', models.FloatField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='api.farm')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='api.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('cause', models.CharField(blank=True, max_length=255, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to='api.farm')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death', to='api.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sale_price', models.FloatField()),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='api.purchase')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='SanitaryProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('protocol_type', models.CharField(max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='api.purchase')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Sublocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_hectares', models.FloatField(blank=True, null=True)),
                ('geo_json_data', models.TextField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_sublocations', to='api.farm')),
                ('parent_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_changes', to='api.farm')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='api.location')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_changes', to='api.purchase')),
                ('sublocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='api.sublocation')),
            ],
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('weight_kg', models.FloatField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightings', to='api.purchase')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightings', to='api.farm')),
            ],
        ),
    ]
